"""Add Town + town_id to User & Listing

Revision ID: 1f1836972922
Revises: 26c9b1b3248b
Create Date: 2025-08-23 12:42:46.685933

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1f1836972922'
down_revision = '26c9b1b3248b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_listing')
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('town_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_listing_town_id'), ['town_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_listing_town_id_town'), 'town', ['town_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('town_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_town_id'), ['town_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_user_town_id_town'), 'town', ['town_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_town_id_town'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_town_id'))
        batch_op.drop_column('town_id')

    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_listing_town_id_town'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_listing_town_id'))
        batch_op.drop_column('town_id')

    op.create_table('_alembic_tmp_listing',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('coordinateX', sa.FLOAT(), nullable=True),
    sa.Column('coordinateY', sa.FLOAT(), nullable=True),
    sa.Column('location_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date_event', sa.DATE(), nullable=False),
    sa.Column('contact_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=64), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('status_enum', sa.VARCHAR(length=8), nullable=False),
    sa.Column('town_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_listing_category_id_category')),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_listing_owner_id_user')),
    sa.ForeignKeyConstraint(['town_id'], ['town.id'], name=op.f('fk_listing_town_id_town'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing'))
    )
    # ### end Alembic commands ###
