"""Add The comment section

Revision ID: 1f92eb52550f
Revises: 707e84924e6a
Create Date: 2025-08-18 17:40:02.903896

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1f92eb52550f'
down_revision = '707e84924e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('commenter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commenter_id'], ['user.id'], name=op.f('fk_comment_commenter_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    op.create_table('comment_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name=op.f('fk_comment_image_comment_id_comment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment_image'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_image')
    op.drop_table('comment')
    # ### end Alembic commands ###
