"""add comment status

Revision ID: 25f522e6b2e1
Revises: 1f1836972922
Create Date: 2025-08-24 00:33:40.346708

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '25f522e6b2e1'
down_revision = '1f1836972922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', name='commentstatus'), server_default='PENDING', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
