"""add listing_id to Comment & fix relationships

Revision ID: 26c9b1b3248b
Revises: 1f92eb52550f
Create Date: 2025-08-18 18:09:33.970784

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '26c9b1b3248b'
down_revision = '1f92eb52550f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_comment_listing_id_listing'), 'listing', ['listing_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_listing_id_listing'), type_='foreignkey')
        batch_op.drop_column('listing_id')

    # ### end Alembic commands ###
