"""add search columns (nullable)

Revision ID: 45a1031b1f49
Revises: eea3921981db
Create Date: 2025-08-24 20:40:09.355249

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '45a1031b1f49'
down_revision = 'eea3921981db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_search', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_search', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_listing_description_search'), ['description_search'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_title_search'), ['title_search'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_title_search'))
        batch_op.drop_index(batch_op.f('ix_listing_description_search'))
        batch_op.drop_column('description_search')
        batch_op.drop_column('title_search')

    # ### end Alembic commands ###
