"""Add ListingImage model for multiple image

Revision ID: 707e84924e6a
Revises: d0e65b58b54d
Create Date: 2025-08-18 11:38:12.623872

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '707e84924e6a'
down_revision = 'd0e65b58b54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], name=op.f('fk_listing_image_listing_id_listing')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing_image'))
    )
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=255), nullable=True))

    op.drop_table('listing_image')
    # ### end Alembic commands ###
