"""Adding the notify for the users in the datamodel

Revision ID: bffdcd2814a7
Revises: 25f522e6b2e1
Create Date: 2025-08-24 01:33:16.923033

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bffdcd2814a7'
down_revision = '25f522e6b2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('notify_town_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notify_category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_notify_category_id'), ['notify_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notify_town_id'), ['notify_town_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_user_notify_town_id_town'), 'town', ['notify_town_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_notify_category_id_category'), 'category', ['notify_category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_notify_category_id_category'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_notify_town_id_town'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_notify_town_id'))
        batch_op.drop_index(batch_op.f('ix_user_notify_category_id'))
        batch_op.drop_column('notify_category_id')
        batch_op.drop_column('notify_town_id')
        batch_op.drop_column('notify_enabled')

    # ### end Alembic commands ###
