"""sync models

Revision ID: eea3921981db
Revises: bffdcd2814a7
Create Date: 2025-08-24 11:13:09.003601

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'eea3921981db'
down_revision = 'bffdcd2814a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.alter_column('town_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.alter_column('town_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
