"""add search columns

Revision ID: f5b0f9c7740c
Revises: eea3921981db
Create Date: 2025-08-24 20:38:01.680740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b0f9c7740c'
down_revision = 'eea3921981db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_search', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('description_search', sa.Text(), nullable=False))
        batch_op.create_index(batch_op.f('ix_listing_description_search'), ['description_search'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_title_search'), ['title_search'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_title_search'))
        batch_op.drop_index(batch_op.f('ix_listing_description_search'))
        batch_op.drop_column('description_search')
        batch_op.drop_column('title_search')

    # ### end Alembic commands ###
